/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvolutionRouteImport } from './routes/evolution'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsistencyRouteImport } from './routes/consistency'
import { Route as BlockBusterRouteImport } from './routes/block-buster'
import { Route as AlterEgoRouteImport } from './routes/alter-ego'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolutionRoute = EvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsistencyRoute = ConsistencyRouteImport.update({
  id: '/consistency',
  path: '/consistency',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockBusterRoute = BlockBusterRouteImport.update({
  id: '/block-buster',
  path: '/block-buster',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterEgoRoute = AlterEgoRouteImport.update({
  id: '/alter-ego',
  path: '/alter-ego',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alter-ego': typeof AlterEgoRoute
  '/block-buster': typeof BlockBusterRoute
  '/consistency': typeof ConsistencyRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/evolution': typeof EvolutionRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alter-ego': typeof AlterEgoRoute
  '/block-buster': typeof BlockBusterRoute
  '/consistency': typeof ConsistencyRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/evolution': typeof EvolutionRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alter-ego': typeof AlterEgoRoute
  '/block-buster': typeof BlockBusterRoute
  '/consistency': typeof ConsistencyRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/evolution': typeof EvolutionRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alter-ego'
    | '/block-buster'
    | '/consistency'
    | '/dashboard'
    | '/discover'
    | '/evolution'
    | '/login'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alter-ego'
    | '/block-buster'
    | '/consistency'
    | '/dashboard'
    | '/discover'
    | '/evolution'
    | '/login'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/alter-ego'
    | '/block-buster'
    | '/consistency'
    | '/dashboard'
    | '/discover'
    | '/evolution'
    | '/login'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlterEgoRoute: typeof AlterEgoRoute
  BlockBusterRoute: typeof BlockBusterRoute
  ConsistencyRoute: typeof ConsistencyRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  EvolutionRoute: typeof EvolutionRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolution': {
      id: '/evolution'
      path: '/evolution'
      fullPath: '/evolution'
      preLoaderRoute: typeof EvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consistency': {
      id: '/consistency'
      path: '/consistency'
      fullPath: '/consistency'
      preLoaderRoute: typeof ConsistencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/block-buster': {
      id: '/block-buster'
      path: '/block-buster'
      fullPath: '/block-buster'
      preLoaderRoute: typeof BlockBusterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alter-ego': {
      id: '/alter-ego'
      path: '/alter-ego'
      fullPath: '/alter-ego'
      preLoaderRoute: typeof AlterEgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlterEgoRoute: AlterEgoRoute,
  BlockBusterRoute: BlockBusterRoute,
  ConsistencyRoute: ConsistencyRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  EvolutionRoute: EvolutionRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
